version: '3.3'

services:

  qdrant:
    image: qdrant/qdrant:v1.11.5
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant_data:/qdrant/storage

  llama-index:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - documents:/app/documents
    depends_on:
      - qdrant
      - ollama
      
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
  qdrant_data:
  documents: